import type { PublicSurfaceSlice } from '@/lib/public-surface/types';

import {
  apiCatalogPath,
  articleEventIcsPattern,
  articleMarkdownPattern,
  articlePattern,
  articlesDataPath,
  articlesOpenApiPath,
  articlesSchemaPath,
  feedPath,
  llmsFullPath,
  llmsPath,
  monthMarkdownPattern,
  monthPattern,
  newsMarkdownPath,
  newsPath,
  tagMarkdownPattern,
  tagPattern,
  tagsMarkdownPath,
  tagsPath,
  yearMarkdownPattern,
  yearPattern,
} from './routes';

export const newsPublicSurfaceSlice = {
  owner: {
    id: 'news',
    label: 'Новости',
    entryPath: newsPath(),
  },
  surfaces: [
    {
      id: 'news:index',
      label: 'Новости',
      path: newsPath(),
      mediaType: 'text/html',
      cacheClass: 'html',
      discoveryRoles: ['section-entry'],
      catalogRole: 'anchor',
    },
    {
      id: 'news:index-markdown',
      label: 'Markdown-версия новостей',
      path: newsMarkdownPath(),
      mediaType: 'text/markdown',
      cacheClass: 'markdown',
      discoveryRoles: ['markdown-companion'],
      catalogRole: 'item',
    },
    {
      id: 'news:year',
      label: 'Годовой архив новостей',
      routePattern: yearPattern(),
      mediaType: 'text/html',
      cacheClass: 'html',
      discoveryRoles: ['detail-page'],
    },
    {
      id: 'news:year-markdown',
      label: 'Markdown-версия годового архива новостей',
      routePattern: yearMarkdownPattern(),
      mediaType: 'text/markdown',
      cacheClass: 'markdown',
      discoveryRoles: ['markdown-companion'],
    },
    {
      id: 'news:month',
      label: 'Месячный архив новостей',
      routePattern: monthPattern(),
      mediaType: 'text/html',
      cacheClass: 'html',
      discoveryRoles: ['detail-page'],
    },
    {
      id: 'news:month-markdown',
      label: 'Markdown-версия месячного архива новостей',
      routePattern: monthMarkdownPattern(),
      mediaType: 'text/markdown',
      cacheClass: 'markdown',
      discoveryRoles: ['markdown-companion'],
    },
    {
      id: 'news:article',
      label: 'Страница новости',
      routePattern: articlePattern(),
      mediaType: 'text/html',
      cacheClass: 'html',
      discoveryRoles: ['detail-page'],
    },
    {
      id: 'news:article-markdown',
      label: 'Markdown-версия новости',
      routePattern: articleMarkdownPattern(),
      mediaType: 'text/markdown',
      cacheClass: 'markdown',
      discoveryRoles: ['markdown-companion'],
    },
    {
      id: 'news:article-event-ics',
      label: 'Календарное событие новости',
      routePattern: articleEventIcsPattern(),
      mediaType: 'text/calendar',
      cacheClass: 'static',
      discoveryRoles: ['download'],
    },
    {
      id: 'news:tags',
      label: 'Теги новостей',
      path: tagsPath(),
      mediaType: 'text/html',
      cacheClass: 'html',
      discoveryRoles: ['detail-page'],
    },
    {
      id: 'news:tags-markdown',
      label: 'Markdown-версия тегов новостей',
      path: tagsMarkdownPath(),
      mediaType: 'text/markdown',
      cacheClass: 'markdown',
      discoveryRoles: ['markdown-companion'],
    },
    {
      id: 'news:tag',
      label: 'Страница тега новостей',
      routePattern: tagPattern(),
      mediaType: 'text/html',
      cacheClass: 'html',
      discoveryRoles: ['detail-page'],
    },
    {
      id: 'news:tag-markdown',
      label: 'Markdown-версия тега новостей',
      routePattern: tagMarkdownPattern(),
      mediaType: 'text/markdown',
      cacheClass: 'markdown',
      discoveryRoles: ['markdown-companion'],
    },
    {
      id: 'news:data',
      label: 'Основная машиночитаемая лента новостей',
      path: articlesDataPath(),
      mediaType: 'application/json',
      cacheClass: 'data',
      discoveryRoles: ['data-feed', 'root-catalog'],
      catalogRole: 'item',
    },
    {
      id: 'news:rss',
      label: 'RSS-лента новостей',
      path: feedPath(),
      mediaType: 'application/rss+xml',
      cacheClass: 'feed',
      discoveryRoles: ['data-feed'],
      catalogRole: 'item',
    },
    {
      id: 'news:schema',
      label: 'JSON Schema ленты новостей',
      path: articlesSchemaPath(),
      mediaType: 'application/schema+json',
      cacheClass: 'schema',
      discoveryRoles: ['schema'],
      catalogRole: 'service-desc',
    },
    {
      id: 'news:openapi',
      label: 'OpenAPI ленты новостей',
      path: articlesOpenApiPath(),
      mediaType: 'application/vnd.oai.openapi+json',
      cacheClass: 'schema',
      discoveryRoles: ['schema'],
      catalogRole: 'service-desc',
    },
    {
      id: 'news:api-catalog',
      label: 'Каталог API новостей',
      path: apiCatalogPath(),
      mediaType: 'application/linkset+json',
      cacheClass: 'catalog',
      discoveryRoles: ['api-catalog', 'root-catalog'],
      catalogRole: 'service-desc',
      sectionCatalogRole: false,
    },
    {
      id: 'news:llms',
      label: 'Агентный обзор новостей',
      path: llmsPath(),
      mediaType: 'text/plain',
      cacheClass: 'static',
      discoveryRoles: ['llms', 'root-catalog'],
      catalogRole: 'item',
    },
    {
      id: 'news:llms-full',
      label: 'Подробный обзор новостей',
      path: llmsFullPath(),
      mediaType: 'text/plain',
      cacheClass: 'static',
      discoveryRoles: ['llms'],
      catalogRole: 'item',
    },
  ],
} satisfies PublicSurfaceSlice;
