import type { PublicSurfaceSlice } from '@/lib/public-surface/types';

import {
  peopleApiCatalogPath,
  peopleDataPath,
  peopleLlmsFullPath,
  peopleLlmsPath,
  peopleMarkdownPath,
  peopleOpenApiPath,
  peopleSchemaPath,
  personMarkdownPattern,
  personPattern,
} from './routes';

export const peoplePublicSurfaceSlice = {
  owner: {
    id: 'people',
    label: 'Люди',
    entryPath: peopleMarkdownPath(),
  },
  surfaces: [
    {
      id: 'people:index-markdown',
      label: 'Markdown-обзор профилей людей без публичного HTML-индекса',
      path: peopleMarkdownPath(),
      mediaType: 'text/markdown',
      cacheClass: 'markdown',
      discoveryRoles: ['section-entry', 'markdown-companion'],
      catalogRole: 'anchor',
    },
    {
      id: 'people:profile',
      label: 'Профиль человека',
      routePattern: personPattern(),
      mediaType: 'text/html',
      cacheClass: 'html',
      discoveryRoles: ['detail-page'],
    },
    {
      id: 'people:profile-markdown',
      label: 'Markdown-версия профиля человека',
      routePattern: personMarkdownPattern(),
      mediaType: 'text/markdown',
      cacheClass: 'markdown',
      discoveryRoles: ['markdown-companion'],
    },
    {
      id: 'people:data',
      label: 'Основная машиночитаемая лента профилей людей',
      path: peopleDataPath(),
      mediaType: 'application/json',
      cacheClass: 'data',
      discoveryRoles: ['data-feed', 'root-catalog'],
      catalogRole: 'item',
    },
    {
      id: 'people:schema',
      label: 'JSON Schema ленты профилей людей',
      path: peopleSchemaPath(),
      mediaType: 'application/schema+json',
      cacheClass: 'schema',
      discoveryRoles: ['schema'],
      catalogRole: 'service-desc',
    },
    {
      id: 'people:openapi',
      label: 'OpenAPI ленты профилей людей',
      path: peopleOpenApiPath(),
      mediaType: 'application/vnd.oai.openapi+json',
      cacheClass: 'schema',
      discoveryRoles: ['schema'],
      catalogRole: 'service-desc',
    },
    {
      id: 'people:api-catalog',
      label: 'Каталог API профилей людей',
      path: peopleApiCatalogPath(),
      mediaType: 'application/linkset+json',
      cacheClass: 'catalog',
      discoveryRoles: ['api-catalog', 'root-catalog'],
      catalogRole: 'service-desc',
      sectionCatalogRole: false,
    },
    {
      id: 'people:llms',
      label: 'Агентный обзор профилей людей',
      path: peopleLlmsPath(),
      mediaType: 'text/plain',
      cacheClass: 'static',
      discoveryRoles: ['llms', 'root-catalog'],
      catalogRole: 'item',
    },
    {
      id: 'people:llms-full',
      label: 'Подробный обзор профилей людей',
      path: peopleLlmsFullPath(),
      mediaType: 'text/plain',
      cacheClass: 'static',
      discoveryRoles: ['llms'],
      catalogRole: 'item',
    },
  ],
} satisfies PublicSurfaceSlice;
