import type {
  PublicSurface,
  PublicSurfaceId,
  PublicSurfaceLinksetItem,
  PublicSurfaceOwner,
  PublicSurfaceOwnerId,
  PublicSurfaceRegistry,
  PublicSurfaceSlice,
} from './types';
import { comparePublicSurfaceSlice } from '@/compare/lib/public-surface';
import {
  apiCatalogPath as newsApiCatalogPath,
  articleEventIcsPattern,
  articleMarkdownPattern,
  articlePattern,
  articlesDataPath,
  articlesOpenApiPath,
  articlesSchemaPath,
  feedPath as newsFeedPath,
  llmsFullPath as newsLlmsFullPath,
  llmsPath as newsLlmsPath,
  monthMarkdownPattern,
  monthPattern,
  newsMarkdownPath,
  newsPath,
  tagsMarkdownPath,
  tagsPath,
  tagMarkdownPattern,
  tagPattern,
  yearMarkdownPattern,
  yearPattern,
} from '@/lib/news/routes';
import {
  peopleApiCatalogPath,
  peopleDataPath,
  peopleLlmsFullPath,
  peopleLlmsPath,
  peopleMarkdownPath,
  peopleOpenApiPath,
  peopleSchemaPath,
  personMarkdownPattern,
  personPattern,
} from '@/lib/people/routes';
import { reglamentPublicSurfaceSlice } from '@/lib/reglament/public-surface';
import {
  statusApiCatalogPath,
  statusDataPath,
  statusFeedPath,
  statusIncidentMarkdownPattern,
  statusIncidentPattern,
  statusLlmsFullPath,
  statusLlmsPath,
  statusMarkdownPath,
  statusOpenApiPath,
  statusPath,
  statusSchemaPath,
  statusServiceMarkdownPattern,
  statusServicePattern,
} from '@/lib/status/routes';
import {
  siteApiCatalogPath,
  siteLlmsFullPath,
  siteLlmsPath,
  siteMarkdownPath,
} from '@/lib/root-routes';
import { siteSkillsPath } from '@/lib/skills';

const absoluteUrl = (root: string, path: string): string =>
  new URL(path.replace(/^\//, ''), `${root.replace(/\/$/, '')}/`).toString();

export const surfaceHref = (root: string, surface: PublicSurface): string =>
  surface.path === undefined
    ? surface.routePattern
    : absoluteUrl(root, surface.path);

export const surfaceToLinksetItem = (
  root: string,
  surface: PublicSurface,
): PublicSurfaceLinksetItem => ({
  href: surfaceHref(root, surface),
  type: surface.mediaType,
  ...(surface.linkRelations?.length
    ? { rel: surface.linkRelations.map((link) => link.rel) }
    : {}),
  ...(surface.label ? { title: surface.label } : {}),
});

export const createPublicSurfaceRegistry = (
  slices: readonly PublicSurfaceSlice[],
): PublicSurfaceRegistry => {
  const sections = slices.map((slice) => slice.owner);
  const surfaces = slices.flatMap((slice) => slice.surfaces);
  const ownerBySurfaceId = new Map<PublicSurfaceId, PublicSurfaceOwner>(
    slices.flatMap((slice) =>
      slice.surfaces.map((surface) => [surface.id, slice.owner] as const),
    ),
  );
  const surfacesByOwnerId = new Map<
    PublicSurfaceOwnerId,
    readonly PublicSurface[]
  >(slices.map((slice) => [slice.owner.id, slice.surfaces] as const));

  return {
    sections,
    surfaces,
    slices,
    surfaceOwner: (surfaceId) => ownerBySurfaceId.get(surfaceId),
    surfacesByOwner: (ownerId) => surfacesByOwnerId.get(ownerId) ?? [],
  };
};

export const rootPublicSurfaceSlice = {
  owner: {
    id: 'root',
    label: 'Корневой сайт',
    entryPath: '/',
  },
  surfaces: [
    {
      id: 'root:index',
      label: 'Главная страница сайта',
      path: '/',
      mediaType: 'text/html',
      cacheClass: 'html',
      discoveryRoles: ['section-entry'],
      catalogRole: 'anchor',
    },
    {
      id: 'root:index-markdown',
      label: 'Markdown-версия корневой страницы',
      path: siteMarkdownPath(),
      mediaType: 'text/markdown',
      cacheClass: 'markdown',
      discoveryRoles: ['markdown-companion'],
      catalogRole: 'item',
    },
    {
      id: 'root:llms',
      label: 'Короткий обзор корневого сайта',
      path: siteLlmsPath(),
      mediaType: 'text/plain',
      cacheClass: 'static',
      discoveryRoles: ['llms'],
      catalogRole: 'item',
    },
    {
      id: 'root:llms-full',
      label: 'Подробный обзор корневого сайта',
      path: siteLlmsFullPath(),
      mediaType: 'text/plain',
      cacheClass: 'static',
      discoveryRoles: ['llms'],
      catalogRole: 'item',
    },
    {
      id: 'root:api-catalog',
      label: 'Каталог API сайта',
      path: siteApiCatalogPath(),
      mediaType: 'application/linkset+json',
      cacheClass: 'catalog',
      discoveryRoles: ['api-catalog', 'root-catalog'],
      catalogRole: 'service-desc',
      sectionCatalogRole: false,
    },
    {
      id: 'root:skills',
      label: 'Индекс инструкций для автоматического чтения корневого сайта',
      path: siteSkillsPath(),
      mediaType: 'application/json',
      cacheClass: 'data',
      discoveryRoles: ['skill-index'],
      catalogRole: 'item',
    },
  ],
} satisfies PublicSurfaceSlice;

export const newsPublicSurfaceSlice = {
  owner: {
    id: 'news',
    label: 'Новости',
    entryPath: newsPath(),
  },
  surfaces: [
    {
      id: 'news:index',
      label: 'Новости',
      path: newsPath(),
      mediaType: 'text/html',
      cacheClass: 'html',
      discoveryRoles: ['section-entry'],
      catalogRole: 'anchor',
    },
    {
      id: 'news:index-markdown',
      label: 'Markdown-версия новостей',
      path: newsMarkdownPath(),
      mediaType: 'text/markdown',
      cacheClass: 'markdown',
      discoveryRoles: ['markdown-companion'],
      catalogRole: 'item',
    },
    {
      id: 'news:year',
      label: 'Годовой архив новостей',
      routePattern: yearPattern(),
      mediaType: 'text/html',
      cacheClass: 'html',
      discoveryRoles: ['detail-page'],
    },
    {
      id: 'news:year-markdown',
      label: 'Markdown-версия годового архива новостей',
      routePattern: yearMarkdownPattern(),
      mediaType: 'text/markdown',
      cacheClass: 'markdown',
      discoveryRoles: ['markdown-companion'],
    },
    {
      id: 'news:month',
      label: 'Месячный архив новостей',
      routePattern: monthPattern(),
      mediaType: 'text/html',
      cacheClass: 'html',
      discoveryRoles: ['detail-page'],
    },
    {
      id: 'news:month-markdown',
      label: 'Markdown-версия месячного архива новостей',
      routePattern: monthMarkdownPattern(),
      mediaType: 'text/markdown',
      cacheClass: 'markdown',
      discoveryRoles: ['markdown-companion'],
    },
    {
      id: 'news:article',
      label: 'Страница новости',
      routePattern: articlePattern(),
      mediaType: 'text/html',
      cacheClass: 'html',
      discoveryRoles: ['detail-page'],
    },
    {
      id: 'news:article-markdown',
      label: 'Markdown-версия новости',
      routePattern: articleMarkdownPattern(),
      mediaType: 'text/markdown',
      cacheClass: 'markdown',
      discoveryRoles: ['markdown-companion'],
    },
    {
      id: 'news:article-event-ics',
      label: 'Календарное событие новости',
      routePattern: articleEventIcsPattern(),
      mediaType: 'text/calendar',
      cacheClass: 'static',
      discoveryRoles: ['download'],
    },
    {
      id: 'news:tags',
      label: 'Теги новостей',
      path: tagsPath(),
      mediaType: 'text/html',
      cacheClass: 'html',
      discoveryRoles: ['detail-page'],
    },
    {
      id: 'news:tags-markdown',
      label: 'Markdown-версия тегов новостей',
      path: tagsMarkdownPath(),
      mediaType: 'text/markdown',
      cacheClass: 'markdown',
      discoveryRoles: ['markdown-companion'],
    },
    {
      id: 'news:tag',
      label: 'Страница тега новостей',
      routePattern: tagPattern(),
      mediaType: 'text/html',
      cacheClass: 'html',
      discoveryRoles: ['detail-page'],
    },
    {
      id: 'news:tag-markdown',
      label: 'Markdown-версия тега новостей',
      routePattern: tagMarkdownPattern(),
      mediaType: 'text/markdown',
      cacheClass: 'markdown',
      discoveryRoles: ['markdown-companion'],
    },
    {
      id: 'news:data',
      label: 'Основная машиночитаемая лента новостей',
      path: articlesDataPath(),
      mediaType: 'application/json',
      cacheClass: 'data',
      discoveryRoles: ['data-feed', 'root-catalog'],
      catalogRole: 'item',
    },
    {
      id: 'news:rss',
      label: 'RSS-лента новостей',
      path: newsFeedPath(),
      mediaType: 'application/rss+xml',
      cacheClass: 'feed',
      discoveryRoles: ['data-feed'],
      catalogRole: 'item',
    },
    {
      id: 'news:schema',
      label: 'JSON Schema ленты новостей',
      path: articlesSchemaPath(),
      mediaType: 'application/schema+json',
      cacheClass: 'schema',
      discoveryRoles: ['schema'],
      catalogRole: 'service-desc',
    },
    {
      id: 'news:openapi',
      label: 'OpenAPI ленты новостей',
      path: articlesOpenApiPath(),
      mediaType: 'application/vnd.oai.openapi+json',
      cacheClass: 'schema',
      discoveryRoles: ['schema'],
      catalogRole: 'service-desc',
    },
    {
      id: 'news:api-catalog',
      label: 'Каталог API новостей',
      path: newsApiCatalogPath(),
      mediaType: 'application/linkset+json',
      cacheClass: 'catalog',
      discoveryRoles: ['api-catalog', 'root-catalog'],
      catalogRole: 'service-desc',
      sectionCatalogRole: false,
    },
    {
      id: 'news:llms',
      label: 'Агентный обзор новостей',
      path: newsLlmsPath(),
      mediaType: 'text/plain',
      cacheClass: 'static',
      discoveryRoles: ['llms', 'root-catalog'],
      catalogRole: 'item',
    },
    {
      id: 'news:llms-full',
      label: 'Подробный обзор новостей',
      path: newsLlmsFullPath(),
      mediaType: 'text/plain',
      cacheClass: 'static',
      discoveryRoles: ['llms'],
      catalogRole: 'item',
    },
  ],
} satisfies PublicSurfaceSlice;

export const statusPublicSurfaceSlice = {
  owner: {
    id: 'status',
    label: 'Статус сервисов',
    entryPath: statusPath(),
  },
  surfaces: [
    {
      id: 'status:index',
      label: 'Статус сервисов',
      path: statusPath(),
      mediaType: 'text/html',
      cacheClass: 'html',
      discoveryRoles: ['section-entry'],
      catalogRole: 'anchor',
    },
    {
      id: 'status:index-markdown',
      label: 'Markdown-версия статуса',
      path: statusMarkdownPath(),
      mediaType: 'text/markdown',
      cacheClass: 'markdown',
      discoveryRoles: ['markdown-companion'],
      catalogRole: 'item',
    },
    {
      id: 'status:service',
      label: 'Страница сервиса',
      routePattern: statusServicePattern(),
      mediaType: 'text/html',
      cacheClass: 'html',
      discoveryRoles: ['detail-page'],
    },
    {
      id: 'status:service-markdown',
      label: 'Markdown-версия сервиса',
      routePattern: statusServiceMarkdownPattern(),
      mediaType: 'text/markdown',
      cacheClass: 'markdown',
      discoveryRoles: ['markdown-companion'],
    },
    {
      id: 'status:incident',
      label: 'Страница инцидента',
      routePattern: statusIncidentPattern(),
      mediaType: 'text/html',
      cacheClass: 'html',
      discoveryRoles: ['detail-page'],
    },
    {
      id: 'status:incident-markdown',
      label: 'Markdown-версия инцидента',
      routePattern: statusIncidentMarkdownPattern(),
      mediaType: 'text/markdown',
      cacheClass: 'markdown',
      discoveryRoles: ['markdown-companion'],
    },
    {
      id: 'status:data',
      label: 'Основная машиночитаемая лента статуса',
      path: statusDataPath(),
      mediaType: 'application/json',
      cacheClass: 'data',
      discoveryRoles: ['data-feed', 'root-catalog'],
      catalogRole: 'item',
    },
    {
      id: 'status:rss',
      label: 'RSS-лента статуса',
      path: statusFeedPath(),
      mediaType: 'application/rss+xml',
      cacheClass: 'feed',
      discoveryRoles: ['data-feed'],
      catalogRole: 'item',
    },
    {
      id: 'status:schema',
      label: 'JSON Schema ленты статуса',
      path: statusSchemaPath(),
      mediaType: 'application/schema+json',
      cacheClass: 'schema',
      discoveryRoles: ['schema'],
      catalogRole: 'service-desc',
    },
    {
      id: 'status:openapi',
      label: 'OpenAPI ленты статуса',
      path: statusOpenApiPath(),
      mediaType: 'application/vnd.oai.openapi+json',
      cacheClass: 'schema',
      discoveryRoles: ['schema'],
      catalogRole: 'service-desc',
    },
    {
      id: 'status:api-catalog',
      label: 'Каталог API статуса',
      path: statusApiCatalogPath(),
      mediaType: 'application/linkset+json',
      cacheClass: 'catalog',
      discoveryRoles: ['api-catalog', 'root-catalog'],
      catalogRole: 'service-desc',
      sectionCatalogRole: false,
    },
    {
      id: 'status:llms',
      label: 'Агентный обзор статуса',
      path: statusLlmsPath(),
      mediaType: 'text/plain',
      cacheClass: 'static',
      discoveryRoles: ['llms', 'root-catalog'],
      catalogRole: 'item',
    },
    {
      id: 'status:llms-full',
      label: 'Подробный обзор статуса',
      path: statusLlmsFullPath(),
      mediaType: 'text/plain',
      cacheClass: 'static',
      discoveryRoles: ['llms'],
      catalogRole: 'item',
    },
  ],
} satisfies PublicSurfaceSlice;

export const peoplePublicSurfaceSlice = {
  owner: {
    id: 'people',
    label: 'Люди',
    entryPath: peopleMarkdownPath(),
  },
  surfaces: [
    {
      id: 'people:index-markdown',
      label: 'Markdown-обзор профилей людей без публичного HTML-индекса',
      path: peopleMarkdownPath(),
      mediaType: 'text/markdown',
      cacheClass: 'markdown',
      discoveryRoles: ['section-entry', 'markdown-companion'],
      catalogRole: 'anchor',
    },
    {
      id: 'people:profile',
      label: 'Профиль человека',
      routePattern: personPattern(),
      mediaType: 'text/html',
      cacheClass: 'html',
      discoveryRoles: ['detail-page'],
    },
    {
      id: 'people:profile-markdown',
      label: 'Markdown-версия профиля человека',
      routePattern: personMarkdownPattern(),
      mediaType: 'text/markdown',
      cacheClass: 'markdown',
      discoveryRoles: ['markdown-companion'],
    },
    {
      id: 'people:data',
      label: 'Основная машиночитаемая лента профилей людей',
      path: peopleDataPath(),
      mediaType: 'application/json',
      cacheClass: 'data',
      discoveryRoles: ['data-feed', 'root-catalog'],
      catalogRole: 'item',
    },
    {
      id: 'people:schema',
      label: 'JSON Schema ленты профилей людей',
      path: peopleSchemaPath(),
      mediaType: 'application/schema+json',
      cacheClass: 'schema',
      discoveryRoles: ['schema'],
      catalogRole: 'service-desc',
    },
    {
      id: 'people:openapi',
      label: 'OpenAPI ленты профилей людей',
      path: peopleOpenApiPath(),
      mediaType: 'application/vnd.oai.openapi+json',
      cacheClass: 'schema',
      discoveryRoles: ['schema'],
      catalogRole: 'service-desc',
    },
    {
      id: 'people:api-catalog',
      label: 'Каталог API профилей людей',
      path: peopleApiCatalogPath(),
      mediaType: 'application/linkset+json',
      cacheClass: 'catalog',
      discoveryRoles: ['api-catalog', 'root-catalog'],
      catalogRole: 'service-desc',
      sectionCatalogRole: false,
    },
    {
      id: 'people:llms',
      label: 'Агентный обзор профилей людей',
      path: peopleLlmsPath(),
      mediaType: 'text/plain',
      cacheClass: 'static',
      discoveryRoles: ['llms', 'root-catalog'],
      catalogRole: 'item',
    },
    {
      id: 'people:llms-full',
      label: 'Подробный обзор профилей людей',
      path: peopleLlmsFullPath(),
      mediaType: 'text/plain',
      cacheClass: 'static',
      discoveryRoles: ['llms'],
      catalogRole: 'item',
    },
  ],
} satisfies PublicSurfaceSlice;

export const publicSurfaceRegistry = createPublicSurfaceRegistry([
  rootPublicSurfaceSlice,
  newsPublicSurfaceSlice,
  statusPublicSurfaceSlice,
  peoplePublicSurfaceSlice,
  reglamentPublicSurfaceSlice,
  comparePublicSurfaceSlice,
]);

export type {
  PublicSurface,
  PublicSurfaceAcceptNegotiation,
  PublicSurfaceCacheClass,
  PublicSurfaceCatalogRole,
  PublicSurfaceDiscoveryRole,
  PublicSurfaceId,
  PublicSurfaceLinkRelation,
  PublicSurfaceLinksetItem,
  PublicSurfaceOwner,
  PublicSurfaceOwnerId,
  PublicSurfaceRegistry,
  PublicSurfaceSlice,
} from './types';
