import type { PublicSurfaceSlice } from '@/lib/public-surface/types';

import {
  statusApiCatalogPath,
  statusDataPath,
  statusFeedPath,
  statusIncidentMarkdownPattern,
  statusIncidentPattern,
  statusLlmsFullPath,
  statusLlmsPath,
  statusMarkdownPath,
  statusOpenApiPath,
  statusPath,
  statusSchemaPath,
  statusServiceMarkdownPattern,
  statusServicePattern,
} from './routes';

export const statusPublicSurfaceSlice = {
  owner: {
    id: 'status',
    label: 'Статус сервисов',
    entryPath: statusPath(),
  },
  surfaces: [
    {
      id: 'status:index',
      label: 'Статус сервисов',
      path: statusPath(),
      mediaType: 'text/html',
      cacheClass: 'html',
      discoveryRoles: ['section-entry'],
      catalogRole: 'anchor',
    },
    {
      id: 'status:index-markdown',
      label: 'Markdown-версия статуса',
      path: statusMarkdownPath(),
      mediaType: 'text/markdown',
      cacheClass: 'markdown',
      discoveryRoles: ['markdown-companion'],
      catalogRole: 'item',
    },
    {
      id: 'status:service',
      label: 'Страница сервиса',
      routePattern: statusServicePattern(),
      mediaType: 'text/html',
      cacheClass: 'html',
      discoveryRoles: ['detail-page'],
    },
    {
      id: 'status:service-markdown',
      label: 'Markdown-версия сервиса',
      routePattern: statusServiceMarkdownPattern(),
      mediaType: 'text/markdown',
      cacheClass: 'markdown',
      discoveryRoles: ['markdown-companion'],
    },
    {
      id: 'status:incident',
      label: 'Страница инцидента',
      routePattern: statusIncidentPattern(),
      mediaType: 'text/html',
      cacheClass: 'html',
      discoveryRoles: ['detail-page'],
    },
    {
      id: 'status:incident-markdown',
      label: 'Markdown-версия инцидента',
      routePattern: statusIncidentMarkdownPattern(),
      mediaType: 'text/markdown',
      cacheClass: 'markdown',
      discoveryRoles: ['markdown-companion'],
    },
    {
      id: 'status:data',
      label: 'Основная машиночитаемая лента статуса',
      path: statusDataPath(),
      mediaType: 'application/json',
      cacheClass: 'data',
      discoveryRoles: ['data-feed', 'root-catalog'],
      catalogRole: 'item',
    },
    {
      id: 'status:rss',
      label: 'RSS-лента статуса',
      path: statusFeedPath(),
      mediaType: 'application/rss+xml',
      cacheClass: 'feed',
      discoveryRoles: ['data-feed'],
      catalogRole: 'item',
    },
    {
      id: 'status:schema',
      label: 'JSON Schema ленты статуса',
      path: statusSchemaPath(),
      mediaType: 'application/schema+json',
      cacheClass: 'schema',
      discoveryRoles: ['schema'],
      catalogRole: 'service-desc',
    },
    {
      id: 'status:openapi',
      label: 'OpenAPI ленты статуса',
      path: statusOpenApiPath(),
      mediaType: 'application/vnd.oai.openapi+json',
      cacheClass: 'schema',
      discoveryRoles: ['schema'],
      catalogRole: 'service-desc',
    },
    {
      id: 'status:api-catalog',
      label: 'Каталог API статуса',
      path: statusApiCatalogPath(),
      mediaType: 'application/linkset+json',
      cacheClass: 'catalog',
      discoveryRoles: ['api-catalog', 'root-catalog'],
      catalogRole: 'service-desc',
      sectionCatalogRole: false,
    },
    {
      id: 'status:llms',
      label: 'Агентный обзор статуса',
      path: statusLlmsPath(),
      mediaType: 'text/plain',
      cacheClass: 'static',
      discoveryRoles: ['llms', 'root-catalog'],
      catalogRole: 'item',
    },
    {
      id: 'status:llms-full',
      label: 'Подробный обзор статуса',
      path: statusLlmsFullPath(),
      mediaType: 'text/plain',
      cacheClass: 'static',
      discoveryRoles: ['llms'],
      catalogRole: 'item',
    },
  ],
} satisfies PublicSurfaceSlice;
